# SFT Training Configuration for Qwen2.5-VL-7B on SVG Dataset
dataset_name: "darknoon/svg-stack-filtered"
model_name_or_path: "Qwen/Qwen2.5-VL-7B-Instruct"

# Training hyperparameters
per_device_train_batch_size: 2
max_steps: 10000
learning_rate: 5e-6
save_steps: 1000
logging_steps: 10
max_length: 4096

# Model configuration
bf16: true
torch_dtype: "bfloat16"
gradient_checkpointing: true
trust_remote_code: true
attn_implementation: "flash_attention_2"

# Extra configuration
# This isn't working b/c of deepspeed zero-3 not supporting torch.compile
# torch_compile: true
freeze_vision_encoder: true
