# We specify all config items not just defaults
ray_init:
  num_cpus: null
  num_gpus: null

data:
  train_files: darknoon/simple-shapes-svg
  val_files: darknoon/simple-shapes-svg
  prompt_key: shape_name
  answer_key: svg
  image_key: image
  max_prompt_length: 1000
  max_response_length: 1000
  rollout_batch_size: 128
  val_batch_size: 1024
  format_prompt: ./svg_env/svg_format.jinja
  shuffle: true
  seed: 1
  max_pixels: 4194304
  min_pixels: 262144
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: true
  use_kl_loss: false
  use_kl_in_reward: false

actor_rollout_ref:
  model:
    path: Qwen/Qwen2.5-VL-7B-Instruct
    enable_gradient_checkpointing: true
    use_remove_padding: true

  actor:
    strategy: fsdp
    optim:
      lr: 1.0e-5
    ppo_mini_batch_size: 128
    ppo_micro_batch_size_per_gpu: 4
    use_kl_loss: false
    fsdp_config:
      param_offload: true
      optimizer_offload: true

  rollout:
    name: vllm
    mode: sync
    n: 64
    temperature: 1.1
    top_p: 0.99
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_model_parallel_size: 2
    log_prob_micro_batch_size_per_gpu: 20
    free_cache_engine: true

  ref:
    log_prob_micro_batch_size_per_gpu: 20
    fsdp_config:
      param_offload: true

reward:
  reward_function: ./svg_env/svg_rlrf_reward.py:compute_rewards_dict

critic:
  enable: false
  strategy: fsdp

reward_model:
  enable: false

custom_reward_function:
  path: ./svg_env/svg_rlrf_reward.py
  name: compute_rewards_dict

trainer:
  total_epochs: 15
  max_steps: 500
  project_name: svg_rlrf
  experiment_name: qwen2_5_vl_7b_svg_grpo_verl
  logger:
    - console
    - wandb
  nnodes: 1
  n_gpus_per_node: 8
  val_freq: 5
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 5
  save_limit: 3
  save_checkpoint_path: /root/checkpoints/svg_rlrf/qwen2_5_vl_7b_svg_grpo_verl
